#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

FROM centos:7

RUN yum update -y
RUN yum install -y gcc gcc-c++ make python3

WORKDIR /app
ARG PLATFORM
RUN SUFFIX=$(echo ${PLATFORM} | sed 's/86_//') && \
  echo $SUFFIX && \
  curl -O -L https://nodejs.org/download/release/v16.19.0/node-v16.19.0-linux-$SUFFIX.tar.gz && \
  tar zxf node-v16.19.0-linux-$SUFFIX.tar.gz && \
  mv node-v16.19.0-linux-$SUFFIX node-v16.19.0

ENV PATH="/app/node-v16.19.0/bin:$PATH"

CMD ["sh"]
